name: Fetch or Build IQ-TREE 2 Static Library
description: "Checks if the IQ-TREE 2 static library exists, if not then building it."
inputs:
  os:
    description: "Runner OS Name."
    required: true
outputs:
  iqtree2-sha:
    description: "SHA for commit of IQ-TREE 2 static library."
    value: ${{ steps.iqtree2-sha.outputs.iqtree2-sha }}
runs:
  using: "composite"
  steps:
    - id: iqtree2-sha
      name: Get IQ-TREE 2 SHA
      shell: bash
      run: |
        cd iqtree2
        IQ_TREE_2_SHA=$(git rev-parse HEAD)
        echo "iqtree2-sha=${IQ_TREE_2_SHA}" >> "$GITHUB_OUTPUT"

    - uses: actions/cache@v4
      id: cache
      with:
        key: libiqtree-${{ inputs.os }}-${{ steps.iqtree2-sha.outputs.iqtree2-sha }}
        path: src/piqtree/_libiqtree/libiqtree2.a
        lookup-only: true

    - name: Build IQ-TREE
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        if [[ "${{ inputs.os }}" == "ubuntu-latest" ]]; then
        sudo ./build_tools/before_all_linux.sh
        else
        ./build_tools/before_all_mac.sh
        fi
