FROM continuumio/miniconda3

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    zsh \
    sudo \
    wget \
    libeigen3-dev \  
    libboost-all-dev \  
    && rm -rf /var/lib/apt/lists/*

# Set up a non-root user with sudo
RUN useradd -ms /bin/zsh user && echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user

USER user
WORKDIR /home/user/repos

# Clone and build IQ-TREE2
RUN git clone --branch libiqtree https://github.com/iqtree/iqtree2.git /home/user/repos/iqtree2 && \
    cd /home/user/repos/iqtree2 && \
    git submodule init && \
    git submodule update && \
    mkdir build && cd build && \
    cmake -DBUILD_LIB=ON .. && \
    make -j

# Install Oh My Zsh
RUN sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" "" --unattended

# Install zsh autosuggestions
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Install zsh syntax highlighting
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Configure zsh
RUN sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc

# Create a new conda environment with Python 3.12
RUN . /opt/conda/etc/profile.d/conda.sh && \
    /opt/conda/bin/conda create -n c312 python=3.12 -y && \
    conda activate c312

# Initialize conda for zsh shell
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.zshrc && \
    echo "conda activate c312" >> ~/.zshrc  

# Clone the repositories using SSH
WORKDIR /home/user/repos
RUN git clone --branch develop https://github.com/cogent3/cogent3.git /home/user/repos/cogent3 

# Install flit in the conda environment
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate c312 && \
    conda install -c conda-forge flit -y  && \
    pip install pybind11
    
# Install the repositories using flit
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate c312 && \
    cd /home/user/repos/cogent3 && \
    flit install -s 

# Set up the project directory
WORKDIR /home/user/pyiqtree

# Set up zsh as the default shell
SHELL ["/bin/zsh", "-c"]

# Set zsh as the default shell for the container
CMD [ "zsh" ]