name: Build and Push Docker images to GitHub Container Registry

on: [workflow_dispatch]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push Base Docker image
        run: |
          docker build -f .devcontainer/DockerFile . \
            -t ghcr.io/${{ github.repository_owner }}/piqtree2:latest
          docker push ghcr.io/${{ github.repository_owner }}/piqtree2:latest

